### PR TITLE
made my way to the first working version

### PR DESCRIPTION
**Pull request by florian-asche**
Hi,
i did try to install paperless-ngx with this ansible repo and saw, it is not finished. Since i try to install everything with ansible, why not help and try to finish this great work.

I did change some parts like wtf do i need to install a specific commit, your ngx repo already has a great versioning by tags. So i removed that part and added a variable which you can set when you dont want to install a release and compile it yourself by a tagged version.

The playbook is running trough. The ngx is reachable on port 8000 but display only " Paperless-ngx is loading... "

I hope you like!

### CODE REVIEW

**Comment by florian-asche** [comment]
I also removed the "No such file or directory" parts. If you running systems with different language this playbook wont work that way. So i think the stat way i did it should work better.

**Comment by florian-asche** [comment]
Ok, didnt take that much time to fix the loading problem ;)

**Comment by qcasey** [comment]
Hello @florian-asche, thank you for your PR. It was extended upon in #4 and merged into `main`. If you are able to give that a test run and report your findings, we would appreciate it!

**Comment by florian-asche** [comment]
Hey, cool that it find a way. I recently switched to Docker but the old instance is still there. I will give it a try in the next days.

**Pull request closed without merging**
